<?php
/**
 * Created by PhpStorm.
 * User: ingridweil
 * Date: 6/7/18
 * Time: 6:04 PM
 */

namespace AppBundle\Repository;

/**
 * TakingorderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class DailyRevenue extends \Doctrine\ORM\EntityRepository
{

}